### ISSUE TITLE
Initiate polling via automation instead of HA

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-skodaconnect#212]
Is there any mechanism to initate polling of data by automation e.g. in case of starting charging by HA?

_Originally posted by @andreasengelsberg in https://github.com/skodaconnect/homeassistant-skodaconnect/issues/210#issuecomment-1729684986_

**Comment by Farfar** [comment]
> Is there any mechanism to initate polling of data by automation e.g. in case of starting charging by HA?
> 
> _Originally posted by @andreasengelsberg in [#210 (comment)](https://github.com/skodaconnect/homeassistant-skodaconnect/issues/210#issuecomment-1729684986)_

The problem is how to know when to start polling if states aren't polled regularly.
It's possible to implement shortened poll interval under some circumstances such as charging/climatisation.
However if the purpose is to prevent the rate limiting I think it's better to explore other options. One being cache and another "night time" poll interval.

**Comment by WebSpider** [comment]
This will be solved by making the polling interval available to be changed, so you could use automation to influence it. We will not support an automation to start/stop polling.

**Comment by dvx76** [comment]
FWIW, someone on Discord mentioned this might just be natively supported by HA. I haven't tried this myself but in theory:

- Settings -> Devices -> Skoda -> System Options -> Uncheck `Enable polling for updates`
- Use the `homeassistant.update_entity` service to trigger an update on demand
