### ISSUE TITLE
Converting the sensors to be MQTT sensors to avoid reconnections to the car when not available.

### ISSUE THREAD

**Issue by sca075** [skodaconnect/homeassistant-skodaconnect#234]
**Is your feature request related to a problem? Please describe.**
In general this integration is one of the best for car ever made for Home Assistant. The only issue is that wen the car is the garage (living in a building with underground garages) the car can't replay to the queries of the api. As consequence the integration try is attempting to reconnect and goes in error or generate several warning, as well the last values for fuel and milage are not available in Home Assistant anymore.
**Describe the solution you'd like**
convert the HA sensors to MQTT sensors, in this way the last fetched data will be retain in MQTT and always available in HA, this would also allow to create a logic that could detect if the car is unreachable and reduce the polling frequency as result.   
**Describe alternatives you've considered**
Currently I store the last data HA could get and I changed some of the automations and scripts to hold the data, but it is not a permanent solution.  I'm developing an integration too (for vacuums) and have some experience with MQTT, I'm thinking to open a PR as soon to attempt what above. 
**Additional context**
This project is quite well structured, I had a BMW before and the integration was well.. this integration is "simply clever" and knowing how difficult it can be, I would be happy to help somehow.. but please understand it will take a while and I might poke you sometime for some question related to the architecture of the component.. this post is just to inform you about this idea, would be appreciate to know if you are interested on what here proposed.

**Comment by dvx76** [comment]
Doesn't this just move the problem? _Something_ needs to be polling the Skoda API and populate the MQTT broker.

**Comment by sca075** [comment]
@dvx76  correct in any cases it is necessary to pull the data but once the integration get connected and can get the values then as per now those values aren't store somewhere.. it could be possible to send the new value to MQTT and retain it until the next polling cycle..  example: "fuel_level" = 50% -> car in the garage  "fuel_level" = N/A (MQTT sensor is still 50%) -> car out from the garage "fuel_level" = 49% -> update MQTT and retain.. this is the basic idea...

**Comment by dvx76** [comment]
I don't mind keeping this open as an enhancement but I honestly doubt anyone will pick it up. There's probably quite a bit to figure out and it creates two code paths to maintain since not everyone will want a dependency on an MQTT broker.

Alternatives which do not require changing the integration:

- Use a template sensor to store the last known value of another sensor: https://community.home-assistant.io/t/sensor-display-last-known-value-instead-of-unavailable/200081
- Use sql sensor to query to the last known value from the HA DB: https://community.home-assistant.io/t/get-last-recorded-value-and-time-from-history-database-for-a-sensor/319038
- If dead set on MQTT, publish sensor values to MQTT: https://community.home-assistant.io/t/post-sensor-values-to-mqtt/177547

**Comment by sca075** [comment]
I repeat "simply clever" that means, would give it a try, anyhow I also perfectly understand your concerns and agree.. probably just as an embedded option and keeping all in one integration.. would be the best way ;) will check in the meantime what you proposed above as alternatives.. probably as you wrote the solution to this specific case is already there.. will report you what are the "alternatives" tests results.. think this can be helpful in any cases :)

**Comment by dvx76** [comment]
I'm going to close this as honestly I don't see anyone every picking this up.
