### ISSUE TITLE
Connection gets lost to MySkoda Essentials: missing data

### ISSUE THREAD

**Issue by KingT** [skodaconnect/homeassistant-skodaconnect#235]
Hi

I use HA to charge my car when the sun is shining for example, which is a very interesting use case that cannot be performed with the regular Skoda app.

Since a while I have been having issues with the integration of SkodaConnect in HA.
My car was not longer connected and also in the MySkoda Essentials app my car was no longer connecting with error "missing data" and "Request failed with status code 500" as a result.
I finally ended up contacting Skoda support to find out what the cause was. 
I got the following answer:

We’ve received an advanced solution from our technical department. As our colleagues informed us, an API request limit has been introduced to protect our backend infrastructure.

Using any 3rd party application/plugin will cause issues for both MyŠkoda app and the Škoda Connect portal. So, in that case we recommend disconnecting the vehicle from your HomeAssistant network and it will fix your issue.

Are there any of you guys with a similar issue and maybe a fix so I can keep on using this great integration in HA?
Simply removing it makes no sense for the app is fairly useless without any integration if you ask me.

Thanks a lot.

**Comment by dhoogfr** [comment]
I didn't (yet?) had the issue myself, but I have seen other complain about it as well.
For them, reducing the polling rate for the HA integration seems to have fixed the issue.
see for example #215 on how to reduce the polling rate and to which interval

**Comment by KingT** [comment]
Thanks for the feedback. Sorry I did not see the other similar issue before posting here.
The parameter was set to 30s in HA which could be the cause.  As I read from the link you have sent, this would be ideally be set to a higher value like 120 or 180s
I will be trying it out and hopefully it works out.

**Comment by erd82** [comment]
... same as this one: https://github.com/skodaconnect/homeassistant-skodaconnect/issues/220

@KingT: I run this HA integration with 120s polling interval (before I tried 180s) and the issue still exists.

So the "API request limit" introduced by Skoda seems quite obvious. But I am really questioning, if Skoda decides for the right strategy, as the brand becomes more and more unattractive with that ! Limiting or slowing down such developments (like 3rd party integrations) is not an opportunity for Skoda, it's the opposite from my point of view. For me, it is one more reason not choosing Skoda/VW again, once I have to decide for a new car (in a few months I will have to). But this is just a side remark.

@Farfar: Is there still optimization potential in the polling concept of this integration to decrease the overall number of daily API calls?

Does Skoda officially know, accept or even support Home Assistant and this integration?

**Comment by KingT** [comment]
For me it seems to work now.
I did change the pollong interval to 300 and I also removed the app from my phone to make sure there is no "interference".
I also had to wait for at least a day before it started working again in HA, so you might need some patience.
As far as I understand, Skoda has put a limit on the amount of requests that it will handle and when you exceed this limit, things will stop working until the next day when the counters seem to be reset.
Hope this info was helpful for you.

**Comment by dvx76** [comment]
@erd82 

>  Is there still optimization potential in the polling concept of this integration to decrease the overall number of daily API calls?

Yes. There have been discussions on discord to either make the poll interval updateable through a service call, or make the complete update a service call. Both with the goal of allowing customized poll frequencies (e.g. lower at night). Should probably create an issue for it so it's more visible. 

> Does Skoda officially know, accept or even support Home Assistant and this integration?

As far as we know they have no knowledge of it but I would be surprised if nobody from Skoda is reading along. In https://github.com/skodaconnect/homeassistant-skodaconnect/issues/227#issuecomment-1805720818 someone got an email response from Skoda where they state they do not want to actively block third party access to the API.

**Comment by Cypherke** [comment]
FYI, I had the exact same response today from skoda since I was having issues for about a week or 2 now.
`After analysis, our experts would like to inform you that this behaviour in the App and the Web portal, is caused by a 3rd party software that you have installed e.g. Home Assistant. As a backend protection, your vehicle is subsequently disconnected. Please try to disable the 3rd party software with access to your vehicle. Then your vehicle will be available in the MySkoda application all the time.`

**Comment by ChristophCaina** [comment]
> FYI, I had the exact same response today from skoda since I was having issues for about a week or 2 now. `After analysis, our experts would like to inform you that this behaviour in the App and the Web portal, is caused by a 3rd party software that you have installed e.g. Home Assistant. As a backend protection, your vehicle is subsequently disconnected. Please try to disable the 3rd party software with access to your vehicle. Then your vehicle will be available in the MySkoda application all the time.`

According to one of the issues reported here, using a "third party integration" is agains the "Terms of usage" from Skoda / VW Group.

I can somehow understand the company - third party applications can be a risk to their infrastructure, because they are not tested by them and therefore these companies try to block such applications, they should consider to provide an official API to allow a software like HomeAssistant to connect to their services.

I still think, that the community should try to raise this to companies - including VW and other brands - but this would probably also require NabuCasa to be involved... and this, again, might not happen as long as the integration is no CORE integration (including all other VW based forks)...

**Comment by piotrator** [comment]
Today, I got exactly same response from Skoda also :), copy -paste with google translator on the way. Anyhow when I accepted new terms on the app, like 3 days ago, nothing changed. They still close the access on 20:00 CET and restart at 1 AM CET.

**Comment by piotrator** [comment]
Hi. Today I lost connection to skoda-connect. Even that I can log in from web or mobile app, From HA there is a message that "Could not login to Skoda Connect, please check your credentials and verify that the service is working". Seems that skoda blocked such connection now? Anyone has such issue?

**Comment by Farfar** [comment]
This issue is already resolved, please update to latest version.

**Comment by Farfar** [comment]
I realize that I closed this issue hastily, root cause in this issue is VAG restricting API polls per day and nothing we can do anything about.
Restricting poll interval to one every 2 minutes works for most but YMMW since it's based on total amount of requests and if you have multiple third party integrations for your car, smart charging for instance, this will also count.

**Comment by MatejMonika** [comment]
Does somebody alse have issue with connection on Skoda connect directly or over the HA?
